""" 
1) Faça um programa em Python que receba três números e calcule a soma 
deles 
"""


n1 = int(input("Informe um número: "))
n2 = int(input("Informe um número: "))
n3 = int(input("Informe um número: "))

soma = n1 + n2 + n3

print("Soma dos números é: ", soma)


"""
2) Faça um programa em Python que leia dois números inteiros e imprima a 
média aritmética entre esses dois valores. 

"""


n1 = int(input("Informe um número: "))
n2 = int(input("Informe um número: "))

media = (n1 + n2)/2

print("Média dos números é: ", media)



"""
3) Faça um programa em Python que calcule a área do triângulo e apresente o 
resultado.

"""

base = int(input("Informe à base do triângulo: "))
altura = int(input("Informe à altura do triângulo: "))

area = (base * altura)/2

print("Área do triângulo é igual: ", area)


"""

4) Faça um programa em Python que receba o valor de uma conta e um 
percentual de desconto. Calcule o novo valor da conta ao ser aplicado, o 
percentual de desconto e escreva o resultado obtido. 

"""


"""

4) Faça um programa em Python que receba o valor de uma conta e um 
percentual de desconto. Calcule o novo valor da conta ao ser aplicado, o 
percentual de desconto e escreva o resultado obtido. 

"""